STATUT_EN_ATTENTE = "en_attente"
STATUT_VALIDEE = "validée"
STATUT_EXPEDIEE = "expédiée"
STATUT_ANNULEE = "annulée"

STATUTS = (
    STATUT_EN_ATTENTE,
    STATUT_VALIDEE,
    STATUT_EXPEDIEE,
    STATUT_ANNULEE,
)
